
package com.platform.modules.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HrmServicePortType", targetNamespace = "http://localhost/services/HrmService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HrmServicePortType {


    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @return
     *     returns boolean
     */
    @WebMethod(action = "urn:weaver.hrm.webservice.HrmService.changeUserPassword")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    @RequestWrapper(localName = "changeUserPassword", targetNamespace = "http://localhost/services/HrmService", className = "com.platform.modules.webservices.ChangeUserPassword")
    @ResponseWrapper(localName = "changeUserPasswordResponse", targetNamespace = "http://localhost/services/HrmService", className = "com.platform.modules.webservices.ChangeUserPasswordResponse")
    public boolean changeUserPassword(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/HrmService")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost/services/HrmService")
        String in2);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:weaver.hrm.webservice.HrmService.getHrmJobTitleInfoXML")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    @RequestWrapper(localName = "getHrmJobTitleInfoXML", targetNamespace = "http://localhost/services/HrmService", className = "com.platform.modules.webservices.GetHrmJobTitleInfoXML")
    @ResponseWrapper(localName = "getHrmJobTitleInfoXMLResponse", targetNamespace = "http://localhost/services/HrmService", className = "com.platform.modules.webservices.GetHrmJobTitleInfoXMLResponse")
    public String getHrmJobTitleInfoXML(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/HrmService")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost/services/HrmService")
        String in2);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:weaver.hrm.webservice.HrmService.getDepartmentInfoWithPage")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    @RequestWrapper(localName = "getDepartmentInfoWithPage", targetNamespace = "http://localhost/services/HrmService", className = "com.platform.modules.webservices.GetDepartmentInfoWithPage")
    @ResponseWrapper(localName = "getDepartmentInfoWithPageResponse", targetNamespace = "http://localhost/services/HrmService", className = "com.platform.modules.webservices.GetDepartmentInfoWithPageResponse")
    public String getDepartmentInfoWithPage(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        String in0);

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:weaver.hrm.webservice.HrmService.getHrmDepartmentInfoXML")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    @RequestWrapper(localName = "getHrmDepartmentInfoXML", targetNamespace = "http://localhost/services/HrmService", className = "com.platform.modules.webservices.GetHrmDepartmentInfoXML")
    @ResponseWrapper(localName = "getHrmDepartmentInfoXMLResponse", targetNamespace = "http://localhost/services/HrmService", className = "com.platform.modules.webservices.GetHrmDepartmentInfoXMLResponse")
    public String getHrmDepartmentInfoXML(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/HrmService")
        String in1);

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SynSubCompany", action = "urn:weaver.hrm.webservice.HrmService.SynSubCompany")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    @RequestWrapper(localName = "SynSubCompany", targetNamespace = "http://localhost/services/HrmService", className = "com.platform.modules.webservices.SynSubCompany")
    @ResponseWrapper(localName = "SynSubCompanyResponse", targetNamespace = "http://localhost/services/HrmService", className = "com.platform.modules.webservices.SynSubCompanyResponse")
    public String synSubCompany(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/HrmService")
        String in1);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @return
     *     returns com.platform.modules.webservices.ArrayOfJobTitleBean
     */
    @WebMethod(action = "urn:weaver.hrm.webservice.HrmService.getHrmJobTitleInfo")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    @RequestWrapper(localName = "getHrmJobTitleInfo", targetNamespace = "http://localhost/services/HrmService", className = "com.platform.modules.webservices.GetHrmJobTitleInfo")
    @ResponseWrapper(localName = "getHrmJobTitleInfoResponse", targetNamespace = "http://localhost/services/HrmService", className = "com.platform.modules.webservices.GetHrmJobTitleInfoResponse")
    public ArrayOfJobTitleBean getHrmJobTitleInfo(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/HrmService")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost/services/HrmService")
        String in2);

    /**
     * 
     * @param in0
     * @return
     *     returns com.platform.modules.webservices.ArrayOfSubCompanyBean
     */
    @WebMethod(action = "urn:weaver.hrm.webservice.HrmService.getHrmSubcompanyInfo")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    @RequestWrapper(localName = "getHrmSubcompanyInfo", targetNamespace = "http://localhost/services/HrmService", className = "com.platform.modules.webservices.GetHrmSubcompanyInfo")
    @ResponseWrapper(localName = "getHrmSubcompanyInfoResponse", targetNamespace = "http://localhost/services/HrmService", className = "com.platform.modules.webservices.GetHrmSubcompanyInfoResponse")
    public ArrayOfSubCompanyBean getHrmSubcompanyInfo(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        String in0);

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SynDepartment", action = "urn:weaver.hrm.webservice.HrmService.SynDepartment")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    @RequestWrapper(localName = "SynDepartment", targetNamespace = "http://localhost/services/HrmService", className = "com.platform.modules.webservices.SynDepartment")
    @ResponseWrapper(localName = "SynDepartmentResponse", targetNamespace = "http://localhost/services/HrmService", className = "com.platform.modules.webservices.SynDepartmentResponse")
    public String synDepartment(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/HrmService")
        String in1);

    /**
     * 
     * @param in5
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns com.platform.modules.webservices.ArrayOfUserBean
     */
    @WebMethod(action = "urn:weaver.hrm.webservice.HrmService.getHrmUserInfo")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    @RequestWrapper(localName = "getHrmUserInfo", targetNamespace = "http://localhost/services/HrmService", className = "com.platform.modules.webservices.GetHrmUserInfo")
    @ResponseWrapper(localName = "getHrmUserInfoResponse", targetNamespace = "http://localhost/services/HrmService", className = "com.platform.modules.webservices.GetHrmUserInfoResponse")
    public ArrayOfUserBean getHrmUserInfo(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/HrmService")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost/services/HrmService")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://localhost/services/HrmService")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://localhost/services/HrmService")
        String in4,
        @WebParam(name = "in5", targetNamespace = "http://localhost/services/HrmService")
        String in5);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @return
     *     returns boolean
     */
    @WebMethod(action = "urn:weaver.hrm.webservice.HrmService.checkUser")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    @RequestWrapper(localName = "checkUser", targetNamespace = "http://localhost/services/HrmService", className = "com.platform.modules.webservices.CheckUser")
    @ResponseWrapper(localName = "checkUserResponse", targetNamespace = "http://localhost/services/HrmService", className = "com.platform.modules.webservices.CheckUserResponse")
    public boolean checkUser(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/HrmService")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost/services/HrmService")
        String in2);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:weaver.hrm.webservice.HrmService.getJobtitleInfoWithPage")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    @RequestWrapper(localName = "getJobtitleInfoWithPage", targetNamespace = "http://localhost/services/HrmService", className = "com.platform.modules.webservices.GetJobtitleInfoWithPage")
    @ResponseWrapper(localName = "getJobtitleInfoWithPageResponse", targetNamespace = "http://localhost/services/HrmService", className = "com.platform.modules.webservices.GetJobtitleInfoWithPageResponse")
    public String getJobtitleInfoWithPage(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        String in0);

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SynHrmResource", action = "urn:weaver.hrm.webservice.HrmService.SynHrmResource")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    @RequestWrapper(localName = "SynHrmResource", targetNamespace = "http://localhost/services/HrmService", className = "com.platform.modules.webservices.SynHrmResource")
    @ResponseWrapper(localName = "SynHrmResourceResponse", targetNamespace = "http://localhost/services/HrmService", className = "com.platform.modules.webservices.SynHrmResourceResponse")
    public String synHrmResource(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/HrmService")
        String in1);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:weaver.hrm.webservice.HrmService.getHrmUserImage")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    @RequestWrapper(localName = "getHrmUserImage", targetNamespace = "http://localhost/services/HrmService", className = "com.platform.modules.webservices.GetHrmUserImage")
    @ResponseWrapper(localName = "getHrmUserImageResponse", targetNamespace = "http://localhost/services/HrmService", className = "com.platform.modules.webservices.GetHrmUserImageResponse")
    public String getHrmUserImage(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/HrmService")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost/services/HrmService")
        String in2);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:weaver.hrm.webservice.HrmService.sycHrmUserImage")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    @RequestWrapper(localName = "sycHrmUserImage", targetNamespace = "http://localhost/services/HrmService", className = "com.platform.modules.webservices.SycHrmUserImage")
    @ResponseWrapper(localName = "sycHrmUserImageResponse", targetNamespace = "http://localhost/services/HrmService", className = "com.platform.modules.webservices.SycHrmUserImageResponse")
    public String sycHrmUserImage(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        String in0);

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns com.platform.modules.webservices.ArrayOfDepartmentBean
     */
    @WebMethod(action = "urn:weaver.hrm.webservice.HrmService.getHrmDepartmentInfo")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    @RequestWrapper(localName = "getHrmDepartmentInfo", targetNamespace = "http://localhost/services/HrmService", className = "com.platform.modules.webservices.GetHrmDepartmentInfo")
    @ResponseWrapper(localName = "getHrmDepartmentInfoResponse", targetNamespace = "http://localhost/services/HrmService", className = "com.platform.modules.webservices.GetHrmDepartmentInfoResponse")
    public ArrayOfDepartmentBean getHrmDepartmentInfo(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/HrmService")
        String in1);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:weaver.hrm.webservice.HrmService.getHrmUserInfoWithPage")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    @RequestWrapper(localName = "getHrmUserInfoWithPage", targetNamespace = "http://localhost/services/HrmService", className = "com.platform.modules.webservices.GetHrmUserInfoWithPage")
    @ResponseWrapper(localName = "getHrmUserInfoWithPageResponse", targetNamespace = "http://localhost/services/HrmService", className = "com.platform.modules.webservices.GetHrmUserInfoWithPageResponse")
    public String getHrmUserInfoWithPage(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:weaver.hrm.webservice.HrmService.getHrmSubcompanyInfoWithPage")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    @RequestWrapper(localName = "getHrmSubcompanyInfoWithPage", targetNamespace = "http://localhost/services/HrmService", className = "com.platform.modules.webservices.GetHrmSubcompanyInfoWithPage")
    @ResponseWrapper(localName = "getHrmSubcompanyInfoWithPageResponse", targetNamespace = "http://localhost/services/HrmService", className = "com.platform.modules.webservices.GetHrmSubcompanyInfoWithPageResponse")
    public String getHrmSubcompanyInfoWithPage(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        String in0);

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SynJobtitle", action = "urn:weaver.hrm.webservice.HrmService.SynJobtitle")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    @RequestWrapper(localName = "SynJobtitle", targetNamespace = "http://localhost/services/HrmService", className = "com.platform.modules.webservices.SynJobtitle")
    @ResponseWrapper(localName = "SynJobtitleResponse", targetNamespace = "http://localhost/services/HrmService", className = "com.platform.modules.webservices.SynJobtitleResponse")
    public String synJobtitle(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/HrmService")
        String in1);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:weaver.hrm.webservice.HrmService.getHrmSubcompanyInfoXML")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    @RequestWrapper(localName = "getHrmSubcompanyInfoXML", targetNamespace = "http://localhost/services/HrmService", className = "com.platform.modules.webservices.GetHrmSubcompanyInfoXML")
    @ResponseWrapper(localName = "getHrmSubcompanyInfoXMLResponse", targetNamespace = "http://localhost/services/HrmService", className = "com.platform.modules.webservices.GetHrmSubcompanyInfoXMLResponse")
    public String getHrmSubcompanyInfoXML(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        String in0);

    /**
     * 
     * @param in5
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:weaver.hrm.webservice.HrmService.getHrmUserInfoXML")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    @RequestWrapper(localName = "getHrmUserInfoXML", targetNamespace = "http://localhost/services/HrmService", className = "com.platform.modules.webservices.GetHrmUserInfoXML")
    @ResponseWrapper(localName = "getHrmUserInfoXMLResponse", targetNamespace = "http://localhost/services/HrmService", className = "com.platform.modules.webservices.GetHrmUserInfoXMLResponse")
    public String getHrmUserInfoXML(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/HrmService")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost/services/HrmService")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://localhost/services/HrmService")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://localhost/services/HrmService")
        String in4,
        @WebParam(name = "in5", targetNamespace = "http://localhost/services/HrmService")
        String in5);

}
